src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_politics_list,
	post_events_list,
	post_gist_list,
	post_celeby_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
)

urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^politics/$', post_politics_list, name='politis'),
	url(r'^events/$', post_events_list, name='event'),
	url(r'^gist/$', post_gist_list, name='gist'),
	url(r'^celebs/$', post_celeby_list, name='celes'),
	url(r'^create/$', post_create),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),
]

src/trydjango19/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^posts/', include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/post_list/post_celeb_list.html
{% extends "base.html" %}

		{% block content %}
		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="{% url 'posts:list' %}">Latest</a></li>
					<li><a href="{% url 'posts:politis' %}">Politics</a></li>
					<li><a href="{% url 'posts:gist' %}">Gists</a></li>
					<li><a href="{% url 'posts:event' %}">Events</a></li>
					<li class="active"><a href="{% url 'posts:celes' %}">Celebrities</a></li>
				</ul>
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

		<section class="posts">
			{% for object in queryset_politics_list %}
			<article>
				<header>
					<span class="date">{{ obj.publish }}</span>
					{% if object.draft %}<h3>Draft</h3>{% endif %}{% if object.publish > today %}<h3>Future Post</h3>{% endif %}
					<h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
				</header>
				{% if object.image %}
				<a href="{{ object.get_absolute_url }}" class="image fit"><img src="{{ object.image.url }}" alt="article image" /></a>
				{% endif %}
				<p>{{ object.content|linebreaks|truncatechars:100 }}</p>
				<ul class="actions">
					<li><a href="{{ object.get_absolute_url }}" class="button">Full Story</a></li>
				</ul>
			</article>

			{% endfor %}
		</section>

		<footer>
			<div class="pagination">
				<!--<a href="#" class="previous">Prev</a>-->
				{% if queryset_politics_list.has_previous %}
				<a href="?{{ page_request_var }}={{ queryset_politics_list.previous_page_number }}">Prev.</a>
				{% endif %}
				<a href="#" class="page active"> {{ queryset_politics_list.number }} of {{ queryset_politics_list.paginator.num_pages }}	</a>
				<span class="extra">&hellip;</span>
				{% if queryset_politics_list.has_next %}
					<a href="?{{ page_request_var }}={{ queryset_politics_list.next_page_number }}">Next</a>
					<span class="extra">&hellip;</span>
					<a href="?{{ page_request_var }}={{ queryset_politics_list.paginator.num_pages }}">last &raquo;</a>
				{% endif %}

			</div>
		</footer>

		{% endblock content %}

src/templates/post_list/post_detail.html
{% extends "base.html"%}
{% block content %}
		
		<!-- <div class="col-md-6 offset-md-2">
			{% if instance.image %}
			<img src="{{ instance.image.url }}" class="img-fluid img-responsive" alt="article image"/>
			{% endif %}
			<h1>The {{ title }} <small> -{{ instance.timestamp }}</small></h1>
		
		<p id="readpost">{{ instance.content }}<p/><br/>
		</div> -->

	<div id="main">
		<section class="post">
			<header class="major">
				<span class="date">{{ instance.publish }} <small>{% if instance.draft %} <span style="color: tomato;">Draft</span>{% endif %}</small></span>
				<h1>This is a<br />
				Generic Page</h1>
				<p>Aenean ornare velit lacus varius enim ullamcorper proin aliquam<br />
				facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor<br />
				amet nullam sed etiam veroeros.</p>
			</header>
			{% if instance.image %}
			<div class="image main"><img src="{{ instance.image.url }}" alt="article image" /></div>
			{% endif %}
			<p>{{ instance.content }}</p>
			<p><small>{{ instance.user  }}</small></p>
			<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
		</section>


{% endblock content %}

src/templates/post_list/post_events_list.html
{% extends "base.html" %}

		{% block content %}
		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="{% url 'posts:list' %}">Latest</a></li>
					<li><a href="{% url 'posts:politis' %}">Politics</a></li>
					<li><a href="{% url 'posts:gist' %}">Gists</a></li>
					<li class="active"><a href="{% url 'posts:event' %}">Events</a></li>
					<li><a href="{% url 'posts:celes' %}">Celebrities</a></li>
				</ul>
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

		<section class="posts">
			{% for object in queryset_politics_list %}
			<article>
				<header>
					<span class="date">{{ obj.publish }}</span>
					{% if object.draft %}<h3>Draft</h3>{% endif %}{% if object.publish > today %}<h3>Future Post</h3>{% endif %}
					<h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
				</header>
				{% if object.image %}
				<a href="{{ object.get_absolute_url }}" class="image fit"><img src="{{ object.image.url }}" alt="article image" /></a>
				{% endif %}
				<p>{{ object.content|linebreaks|truncatechars:100 }}</p>
				<ul class="actions">
					<li><a href="{{ object.get_absolute_url }}" class="button">Full Story</a></li>
				</ul>
			</article>

			{% endfor %}
		</section>
			
		<footer>
			<div class="pagination">
				<!--<a href="#" class="previous">Prev</a>-->
				{% if queryset_politics_list.has_previous %}
				<a href="?{{ page_request_var }}={{ queryset_politics_list.previous_page_number }}">Prev.</a>
				{% endif %}
				<a href="#" class="page active"> {{ queryset_politics_list.number }} of {{ queryset_politics_list.paginator.num_pages }}	</a>
				<span class="extra">&hellip;</span>
				{% if queryset_politics_list.has_next %}
					<a href="?{{ page_request_var }}={{ queryset_politics_list.next_page_number }}">Next</a>
					<span class="extra">&hellip;</span>
					<a href="?{{ page_request_var }}={{ queryset_politics_list.paginator.num_pages }}">last &raquo;</a>
				{% endif %}

			</div>
		</footer>

		{% endblock content %}

src/templates/post_list/post_gist_list.html
{% extends "base.html" %}

		{% block content %}
		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="{% url 'posts:list' %}">Latest</a></li>
					<li><a href="{% url 'posts:politis' %}">Politics</a></li>
					<li class="active"><a href="{% url 'posts:gist' %}">Gists</a></li>
					<li><a href="{% url 'posts:event' %}">Events</a></li>
					<li><a href="{% url 'posts:celes' %}">Celebrities</a></li>
				</ul>
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

		<section class="posts">
			{% for object in queryset_politics_list %}
			<article>
				<header>
					<span class="date">{{ obj.publish }}</span>
					{% if object.draft %}<h3>Draft</h3>{% endif %}{% if object.publish > today %}<h3>Future Post</h3>{% endif %}
					<h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
				</header>
				{% if object.image %}
				<a href="{{ object.get_absolute_url }}" class="image fit"><img src="{{ object.image.url }}" alt="article image" /></a>
				{% endif %}
				<p>{{ object.content|linebreaks|truncatechars:100 }}</p>
				<ul class="actions">
					<li><a href="{{ object.get_absolute_url }}" class="button">Full Story</a></li>
				</ul>
			</article>

			{% endfor %}
		</section>

		<footer>
			<div class="pagination">
				<!--<a href="#" class="previous">Prev</a>-->
				{% if queryset_politics_list.has_previous %}
				<a href="?{{ page_request_var }}={{ queryset_politics_list.previous_page_number }}">Prev.</a>
				{% endif %}
				<a href="#" class="page active"> {{ queryset_politics_list.number }} of {{ queryset_politics_list.paginator.num_pages }}	</a>
				<span class="extra">&hellip;</span>
				{% if queryset_politics_list.has_next %}
					<a href="?{{ page_request_var }}={{ queryset_politics_list.next_page_number }}">Next</a>
					<span class="extra">&hellip;</span>
					<a href="?{{ page_request_var }}={{ queryset_politics_list.paginator.num_pages }}">last &raquo;</a>
				{% endif %}

			</div>
		</footer>

		{% endblock content %}

src/templates/post_list/post_list.html
{% extends "base.html" %}

		{% block content %}
		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li class="active"><a href="{% url 'posts:list' %}">Latest</a></li>
					<li><a href="{% url 'posts:politis' %}">Politics</a></li>
					<li><a href="{% url 'posts:gist' %}">Gists</a></li>
					<li><a href="{% url 'posts:event' %}">Events</a></li>
					<li><a href="{% url 'posts:celes' %}">Celebrities</a></li>
				</ul>
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

		<section class="posts">
			{% for obj in object_list %}
			<article>
				<header>
					<span class="date">{{ obj.publish }}</span>
					{% if obj.draft %}<h3>Draft</h3>{% endif %}{% if obj.publish > today %}<h3>Future Post</h3>{% endif %}
					<h2><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h2>
				</header>
				{% if obj.image %}
				<a href="{{ obj.get_absolute_url }}" class="image fit"><img src="{{ obj.image.url }}" alt="article image" /></a>
				{% endif %}
				<p>{{ obj.content|linebreaks|truncatechars:100 }}</p>
				<ul class="actions">
					<li><a href="{{ obj.get_absolute_url }}" class="button">Full Story</a></li>
				</ul>
			</article>

			{% endfor %}
		</section>

		<footer>
			<div class="pagination">
				<!--<a href="#" class="previous">Prev</a>-->
				{% if object_list.has_previous %}
				<a href="?{{ page_request_var }}={{ object_list.previous_page_number }}">Prev.</a>
				{% endif %}
				<a href="#" class="page active"> {{ object_list.number }} of {{ object_list.paginator.num_pages }}	</a>
				<span class="extra">&hellip;</span>
				{% if object_list.has_next %}
					<a href="?{{ page_request_var }}={{ object_list.next_page_number }}">Next</a>
					<span class="extra">&hellip;</span>
					<a href="?{{ page_request_var }}={{ object_list.paginator.num_pages }}">last &raquo;</a>
				{% endif %}

			</div>
		</footer>

		{% endblock content %}

src/templates/post_list/post_politics_list.html
{% extends "base.html" %}

		{% block content %}
		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="{% url 'posts:list' %}">Latest</a></li>
					<li class="active"><a href="{% url 'posts:politis' %}">Politics</a></li>
					<li><a href="{% url 'posts:gist' %}">Gists</a></li>
					<li><a href="{% url 'posts:event' %}">Events</a></li>
					<li><a href="{% url 'posts:celes' %}">Celebrities</a></li>
				</ul>
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

		<section class="posts">
			{% for object in queryset_politics_list %}
			<article>
				<header>
					<span class="date">{{ obj.publish }}</span>
					{% if object.draft %}<h3>Draft</h3>{% endif %}{% if object.publish > today %}<h3>Future Post</h3>{% endif %}
					<h2><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
				</header>
				{% if object.image %}
				<a href="{{ object.get_absolute_url }}" class="image fit"><img src="{{ object.image.url }}" alt="article image" /></a>
				{% endif %}
				<p>{{ object.content|linebreaks|truncatechars:100 }}</p>
				<ul class="actions">
					<li><a href="{{ object.get_absolute_url }}" class="button">Full Story</a></li>
				</ul>
			</article>

			{% endfor %}
		</section>

		<footer>
			<div class="pagination">
				<!--<a href="#" class="previous">Prev</a>-->
				{% if queryset_politics_list.has_previous %}
				<a href="?{{ page_request_var }}={{ queryset_politics_list.previous_page_number }}">Prev.</a>
				{% endif %}
				<a href="#" class="page active"> {{ queryset_politics_list.number }} of {{ queryset_politics_list.paginator.num_pages }}	</a>
				<span class="extra">&hellip;</span>
				{% if queryset_politics_list.has_next %}
					<a href="?{{ page_request_var }}={{ queryset_politics_list.next_page_number }}">Next</a>
					<span class="extra">&hellip;</span>
					<a href="?{{ page_request_var }}={{ queryset_politics_list.paginator.num_pages }}">last &raquo;</a>
				{% endif %}

			</div>
		</footer>

		{% endblock content %}